all:
	gcc 2-1.c -o 2-1
	gcc 2-2.c -o 2-2
	gcc 2-3.c -o 2-3
	gcc 2-4.c -o 2-4
	gcc 2-5.c -o 2-5
	gcc mycp.c -o mycp
	gcc 2-8.c -o 2-8
	gcc 2-9.c -o 2-9
	gcc 2-15.c -o 2-15
	gcc 3-3.c -o 3-3	
	gcc 3-12.c -o 3-12
	gcc 4-2.c -o 4-2

clean:
	rm *.o
